"""Pure domain model for OMP."""

from .errors import (
    CaptureDisabledError,
    ConnectionRevokedError,
    ConsentRequiredError,
    EmbeddingProfileMismatchError,
    IdempotencyConflictError,
    IdempotencyInProgressError,
    ImportConflictError,
    InvalidStateTransitionError,
    NotFoundError,
    OMPError,
    OwnerAccessError,
    RelationConflictError,
    RestoreBlockedByTombstoneError,
    ScopeDeniedError,
    SpaceForbiddenError,
    StorageError,
    ValidationError,
    VersionConflictError,
)
from .memory import Memory, MemoryVersion
from .serialization import SCHEMA_VERSION, memory_from_dict, memory_to_dict
from .types import (
    CaptureConsent,
    ConsentMode,
    ConsentReason,
    EmbeddingDescriptor,
    MemoryState,
    MemoryType,
    Provenance,
    Relation,
    RelationType,
    SourceType,
    utc_now,
)

__all__ = [
    "EmbeddingDescriptor",
    "CaptureDisabledError",
    "ConnectionRevokedError",
    "ConsentRequiredError",
    "CaptureConsent",
    "ConsentMode",
    "ConsentReason",
    "EmbeddingProfileMismatchError",
    "IdempotencyConflictError",
    "IdempotencyInProgressError",
    "ImportConflictError",
    "InvalidStateTransitionError",
    "Memory",
    "MemoryState",
    "MemoryType",
    "MemoryVersion",
    "NotFoundError",
    "OMPError",
    "OwnerAccessError",
    "Provenance",
    "Relation",
    "RelationConflictError",
    "RelationType",
    "SCHEMA_VERSION",
    "SourceType",
    "StorageError",
    "ScopeDeniedError",
    "SpaceForbiddenError",
    "RestoreBlockedByTombstoneError",
    "ValidationError",
    "VersionConflictError",
    "memory_from_dict",
    "memory_to_dict",
    "utc_now",
]
